<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width">
<meta name="theme-color" content="#222"><meta name="generator" content="Hexo 5.4.1">


  <link rel="apple-touch-icon" sizes="180x180" href="/hais-notebook/images/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/hais-notebook/images/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/hais-notebook/images/favicon-16x16.png">
  <link rel="mask-icon" href="/hais-notebook/images/logo.svg" color="#222">

<link rel="stylesheet" href="/hais-notebook/css/main.css">



<link rel="stylesheet" href="/hais-notebook/lib/@fortawesome/fontawesome-free/css/all.min.css" integrity="sha256-DfWjNxDkM94fVBWx1H5BMMp0Zq7luBlV8QRcSES7s+0=" crossorigin="anonymous">

<script class="next-config" data-name="main" type="application/json">{"hostname":"hyuain.github.io","root":"/hais-notebook/","images":"/hais-notebook/images","scheme":"Gemini","darkmode":false,"version":"8.12.1","exturl":false,"sidebar":{"position":"left","display":"post","padding":18,"offset":12},"copycode":{"enable":true,"style":"mac","show_result":true},"bookmark":{"enable":false,"color":"#222","save":"auto"},"mediumzoom":false,"lazyload":false,"pangu":false,"comments":{"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},"stickytabs":false,"motion":{"enable":false,"async":false,"transition":{"post_block":"fadeIn","post_header":"fadeInDown","post_body":"fadeInDown","coll_header":"fadeInLeft","sidebar":"fadeInUp"}},"prism":false,"i18n":{"placeholder":"搜索...","empty":"没有找到任何搜索结果：${query}","hits_time":"找到 ${hits} 个搜索结果（用时 ${time} 毫秒）","hits":"找到 ${hits} 个搜索结果"},"path":"/hais-notebook/search.xml","localsearch":{"enable":true,"trigger":"auto","top_n_per_article":1,"unescape":false,"preload":false}}</script><script src="/hais-notebook/js/config.js"></script>

    <meta name="description" content="本文是 RxJS Error Handling 的翻译。 主要介绍了 catchError、throwError、Finalize、retryWhen、delayWhen 等操作符，以及捕获并替代策略、捕获并重抛策略、重试策略等错误处理方法。">
<meta property="og:type" content="article">
<meta property="og:title" content="翻译：RxJS 中的错误处理">
<meta property="og:url" content="https://hyuain.github.io/hais-notebook/2021/03/03/RxJS-ErrorHandling/index.html">
<meta property="og:site_name" content="Hais Notebook">
<meta property="og:description" content="本文是 RxJS Error Handling 的翻译。 主要介绍了 catchError、throwError、Finalize、retryWhen、delayWhen 等操作符，以及捕获并替代策略、捕获并重抛策略、重试策略等错误处理方法。">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-1.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-2.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-3.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-4.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-5.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-6.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-7.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-8.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-9.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-10.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-11.png">
<meta property="article:published_time" content="2021-03-03T22:47:21.000Z">
<meta property="article:modified_time" content="2021-03-03T22:47:21.000Z">
<meta property="article:author" content="Harvey Zhang">
<meta property="article:tag" content="入门">
<meta property="article:tag" content="RxJS">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-1.png">


<link rel="canonical" href="https://hyuain.github.io/hais-notebook/2021/03/03/RxJS-ErrorHandling/">



<script class="next-config" data-name="page" type="application/json">{"sidebar":"","isHome":false,"isPost":true,"lang":"zh-CN","comments":true,"permalink":"https://hyuain.github.io/hais-notebook/2021/03/03/RxJS-ErrorHandling/","path":"2021/03/03/RxJS-ErrorHandling/","title":"翻译：RxJS 中的错误处理"}</script>

<script class="next-config" data-name="calendar" type="application/json">""</script>
<title>翻译：RxJS 中的错误处理 | Hais Notebook</title>
  





  <noscript>
    <link rel="stylesheet" href="/hais-notebook/css/noscript.css">
  </noscript>
</head>

<body itemscope itemtype="http://schema.org/WebPage">
  <div class="headband"></div>

  <main class="main">
    <header class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-container">
  <div class="site-nav-toggle">
    <div class="toggle" aria-label="切换导航栏" role="button">
        <span class="toggle-line"></span>
        <span class="toggle-line"></span>
        <span class="toggle-line"></span>
    </div>
  </div>

  <div class="site-meta">

    <a href="/hais-notebook/" class="brand" rel="start">
      <i class="logo-line"></i>
      <p class="site-title">Hais Notebook</p>
      <i class="logo-line"></i>
    </a>
  </div>

  <div class="site-nav-right">
    <div class="toggle popup-trigger">
        <i class="fa fa-search fa-fw fa-lg"></i>
    </div>
  </div>
</div>



<nav class="site-nav">
  <ul class="main-menu menu"><li class="menu-item menu-item-home"><a href="/hais-notebook/" rel="section"><i class="fa fa-home fa-fw"></i>首页</a></li><li class="menu-item menu-item-tags"><a href="/hais-notebook/tags/" rel="section"><i class="fa fa-tags fa-fw"></i>标签</a></li><li class="menu-item menu-item-categories"><a href="/hais-notebook/categories/" rel="section"><i class="fa fa-th fa-fw"></i>分类</a></li><li class="menu-item menu-item-archives"><a href="/hais-notebook/archives/" rel="section"><i class="fa fa-archive fa-fw"></i>归档</a></li>
      <li class="menu-item menu-item-search">
        <a role="button" class="popup-trigger"><i class="fa fa-search fa-fw"></i>搜索
        </a>
      </li>
  </ul>
</nav>



  <div class="search-pop-overlay">
    <div class="popup search-popup"><div class="search-header">
  <span class="search-icon">
    <i class="fa fa-search"></i>
  </span>
  <div class="search-input-container">
    <input autocomplete="off" autocapitalize="off" maxlength="80"
           placeholder="搜索..." spellcheck="false"
           type="search" class="search-input">
  </div>
  <span class="popup-btn-close" role="button">
    <i class="fa fa-times-circle"></i>
  </span>
</div>
<div class="search-result-container no-result">
  <div class="search-result-icon">
    <i class="fa fa-spinner fa-pulse fa-5x"></i>
  </div>
</div>

    </div>
  </div>

</div>
        
  
  <div class="toggle sidebar-toggle" role="button">
    <span class="toggle-line"></span>
    <span class="toggle-line"></span>
    <span class="toggle-line"></span>
  </div>

  <aside class="sidebar">

    <div class="sidebar-inner sidebar-nav-active sidebar-toc-active">
      <ul class="sidebar-nav">
        <li class="sidebar-nav-toc">
          文章目录
        </li>
        <li class="sidebar-nav-overview">
          站点概览
        </li>
      </ul>

      <div class="sidebar-panel-container">
        <!--noindex-->
        <div class="post-toc-wrap sidebar-panel">
            <div class="post-toc animated"><ol class="nav"><li class="nav-item nav-level-1"><a class="nav-link" href="#observable-%E4%B8%AD%E7%9A%84%E7%BA%A6%E5%AE%9A%E4%B8%8E%E9%94%99%E8%AF%AF%E5%A4%84%E7%90%86"><span class="nav-number">1.</span> <span class="nav-text">Observable 中的约定与错误处理</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#rxjs-%E4%B8%AD%E7%9A%84-subscribe-%E6%96%B9%E6%B3%95%E4%B8%8E-error-%E5%9B%9E%E8%B0%83"><span class="nav-number">2.</span> <span class="nav-text">RxJS 中的 subscribe 方法与 error 回调</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#%E5%AE%8C%E6%88%90%E8%A1%8C%E4%B8%BA%E7%9A%84%E4%B8%BE%E4%BE%8B"><span class="nav-number">2.1.</span> <span class="nav-text">完成行为的举例</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#subscribe-%E6%96%B9%E6%B3%95%E4%B8%AD%E7%9A%84-error-%E5%9B%9E%E8%B0%83%E5%87%BD%E6%95%B0%E7%9A%84%E5%B1%80%E9%99%90%E6%80%A7"><span class="nav-number">2.2.</span> <span class="nav-text">subscribe 方法中的 error 回调函数的局限性</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#catcherror-%E6%93%8D%E4%BD%9C%E7%AC%A6"><span class="nav-number">3.</span> <span class="nav-text">catchError 操作符</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#catcherror-%E6%98%AF%E5%A6%82%E4%BD%95%E5%B7%A5%E4%BD%9C%E7%9A%84"><span class="nav-number">3.1.</span> <span class="nav-text">catchError 是如何工作的？</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E5%BD%93%E9%94%99%E8%AF%AF%E5%8F%91%E7%94%9F%E6%97%B6%E4%BC%9A%E6%80%8E%E6%A0%B7"><span class="nav-number">3.2.</span> <span class="nav-text">当错误发生时会怎样？</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#%E6%8D%95%E8%8E%B7%E5%B9%B6%E6%9B%BF%E4%BB%A3%E7%AD%96%E7%95%A5the-catch-and-replace-strategy"><span class="nav-number">4.</span> <span class="nav-text">捕获并替代策略（The Catch and Replace Strategy）</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#%E6%8D%95%E8%8E%B7%E5%B9%B6%E9%87%8D%E6%8A%9B%E7%AD%96%E7%95%A5the-catch-and-rethrow-strategy"><span class="nav-number">5.</span> <span class="nav-text">捕获并重抛策略（The Catch and Rethrow Strategy）</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#%E6%8B%86%E8%A7%A3%E6%8D%95%E8%8E%B7%E5%B9%B6%E9%87%8D%E6%8A%9B%E7%AD%96%E7%95%A5"><span class="nav-number">5.1.</span> <span class="nav-text">拆解捕获并重抛策略</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#%E5%9C%A8-observable-%E9%93%BE%E6%9D%A1%E4%B8%AD%E4%BD%BF%E7%94%A8%E5%A4%9A%E6%AC%A1-catcherror"><span class="nav-number">6.</span> <span class="nav-text">在 Observable 链条中使用多次 catchError</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#finalize-%E6%93%8D%E4%BD%9C%E7%AC%A6"><span class="nav-number">7.</span> <span class="nav-text">Finalize 操作符</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#finalize-%E6%93%8D%E4%BD%9C%E7%AC%A6%E7%9A%84%E4%BE%8B%E5%AD%90"><span class="nav-number">7.1.</span> <span class="nav-text">Finalize 操作符的例子</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#%E9%87%8D%E8%AF%95%E7%AD%96%E7%95%A5the-retry-strategy"><span class="nav-number">8.</span> <span class="nav-text">重试策略（The Retry Strategy）</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#%E4%BB%80%E4%B9%88%E6%97%B6%E5%80%99%E9%87%8D%E8%AF%95"><span class="nav-number">8.1.</span> <span class="nav-text">什么时候重试？</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#rxjs-retrywhen-%E6%93%8D%E4%BD%9C%E7%AC%A6%E7%9A%84%E5%AD%90%E5%BC%B9%E5%9B%BE"><span class="nav-number">9.</span> <span class="nav-text">RxJS retryWhen 操作符的子弹图</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#%E6%8B%86%E8%A7%A3-retrywhen-%E6%98%AF%E5%A6%82%E4%BD%95%E5%B7%A5%E4%BD%9C%E7%9A%84"><span class="nav-number">9.1.</span> <span class="nav-text">拆解 retryWhen 是如何工作的</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#%E5%88%9B%E5%BB%BA%E4%B8%80%E4%B8%AA%E9%80%9A%E7%9F%A5%E8%80%85notification-observable"><span class="nav-number">10.</span> <span class="nav-text">创建一个通知者（Notification Observable）</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#%E7%AB%8B%E5%8D%B3%E9%87%8D%E8%AF%95%E7%AD%96%E7%95%A5immediate-retry-strategy"><span class="nav-number">11.</span> <span class="nav-text">立即重试策略（Immediate Retry Strategy）</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#%E7%AB%8B%E5%8D%B3%E9%87%8D%E8%AF%95%E7%AD%96%E7%95%A5%E7%9A%84%E6%8E%A7%E5%88%B6%E5%8F%B0%E8%BE%93%E5%87%BA%E5%86%85%E5%AE%B9"><span class="nav-number">11.1.</span> <span class="nav-text">立即重试策略的控制台输出内容</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#%E5%BB%B6%E8%BF%9F%E9%87%8D%E8%AF%95%E7%AD%96%E7%95%A5delayed-retry-strategy"><span class="nav-number">12.</span> <span class="nav-text">延迟重试策略（Delayed Retry Strategy）</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#%E8%AE%A1%E6%97%B6%E5%99%A8timer-observable%E5%88%9B%E5%BB%BA%E5%87%BD%E6%95%B0"><span class="nav-number">13.</span> <span class="nav-text">计时器（Timer Observable）创建函数</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#delaywhen-%E6%93%8D%E4%BD%9C%E7%AC%A6"><span class="nav-number">14.</span> <span class="nav-text">delayWhen 操作符</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#delaywhen-%E6%93%8D%E4%BD%9C%E7%AC%A6%E7%9A%84%E6%8B%86%E8%A7%A3"><span class="nav-number">14.1.</span> <span class="nav-text">delayWhen 操作符的拆解</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E5%AE%9E%E6%96%BD%E5%BB%B6%E8%BF%9F%E9%87%8D%E8%AF%95%E7%AD%96%E7%95%A5"><span class="nav-number">14.2.</span> <span class="nav-text">实施延迟重试策略</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#%E5%BB%B6%E8%BF%9F%E7%AD%96%E7%95%A5%E7%9A%84%E6%8E%A7%E5%88%B6%E5%8F%B0%E8%BE%93%E5%87%BA%E5%86%85%E5%AE%B9"><span class="nav-number">14.3.</span> <span class="nav-text">延迟策略的控制台输出内容</span></a></li></ol></li></ol></div>
        </div>
        <!--/noindex-->

        <div class="site-overview-wrap sidebar-panel">
          <div class="site-author site-overview-item animated" itemprop="author" itemscope itemtype="http://schema.org/Person">
  <p class="site-author-name" itemprop="name">Harvey Zhang</p>
  <div class="site-description" itemprop="description">海鲜酱的笔记本</div>
</div>
<div class="site-state-wrap site-overview-item animated">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
        <a href="/hais-notebook/archives/">
          <span class="site-state-item-count">60</span>
          <span class="site-state-item-name">日志</span>
        </a>
      </div>
      <div class="site-state-item site-state-categories">
          <a href="/hais-notebook/categories/">
        <span class="site-state-item-count">27</span>
        <span class="site-state-item-name">分类</span></a>
      </div>
      <div class="site-state-item site-state-tags">
          <a href="/hais-notebook/tags/">
        <span class="site-state-item-count">23</span>
        <span class="site-state-item-name">标签</span></a>
      </div>
  </nav>
</div>



        </div>
      </div>
    </div>
  </aside>
  <div class="sidebar-dimmer"></div>


    </header>

    
  <div class="back-to-top" role="button" aria-label="返回顶部">
    <i class="fa fa-arrow-up"></i>
    <span>0%</span>
  </div>

<noscript>
  <div class="noscript-warning">Theme NexT works best with JavaScript enabled</div>
</noscript>


    <div class="main-inner post posts-expand">


  


<div class="post-block">
  
  

  <article itemscope itemtype="http://schema.org/Article" class="post-content" lang="zh-CN">
    <link itemprop="mainEntityOfPage" href="https://hyuain.github.io/hais-notebook/2021/03/03/RxJS-ErrorHandling/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/hais-notebook/images/avatar.gif">
      <meta itemprop="name" content="Harvey Zhang">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Hais Notebook">
      <meta itemprop="description" content="海鲜酱的笔记本">
    </span>

    <span hidden itemprop="post" itemscope itemtype="http://schema.org/CreativeWork">
      <meta itemprop="name" content="翻译：RxJS 中的错误处理 | Hais Notebook">
      <meta itemprop="description" content="">
    </span>
      <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
          翻译：RxJS 中的错误处理
        </h1>

        <div class="post-meta-container">
          <div class="post-meta">
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-calendar"></i>
      </span>
      <span class="post-meta-item-text">发表于</span>

      <time title="创建时间：2021-03-03 22:47:21" itemprop="dateCreated datePublished" datetime="2021-03-03T22:47:21+00:00">2021-03-03</time>
    </span>
    <span class="post-meta-item">
      <span class="post-meta-item-icon">
        <i class="far fa-folder"></i>
      </span>
      <span class="post-meta-item-text">分类于</span>
        <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
          <a href="/hais-notebook/categories/%E5%89%8D%E7%AB%AF/" itemprop="url" rel="index"><span itemprop="name">前端</span></a>
        </span>
          ，
        <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
          <a href="/hais-notebook/categories/%E5%89%8D%E7%AB%AF/RxJS/" itemprop="url" rel="index"><span itemprop="name">RxJS</span></a>
        </span>
    </span>

  
</div>

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">
        <p>本文是 <a target="_blank" rel="noopener" href="https://blog.angular-university.io/rxjs-error-handling/">RxJS Error Handling</a> 的翻译。 主要介绍了 catchError、throwError、Finalize、retryWhen、delayWhen 等操作符，以及捕获并替代策略、捕获并重抛策略、重试策略等错误处理方法。</p>
<span id="more"></span>
<h1 id="observable-中的约定与错误处理">Observable 中的约定与错误处理</h1>
<p>为了理解 RxJS 中的错误处理，我们需要先知道尽管数据流可以不发送值，也可以发送多个值，但 <strong>一个数据流（stream）只能输出一次错误</strong>。我们做出如此的约定，因为在实践中我们所观察（observe）的所有的流都是这样工作的，比如可能发生错误的网络请求等。</p>
<p>一个流可以顺利完成（complete），这意味着：</p>
<ul>
<li>一个流结束了他的生命周期，在此期间没有发生任何错误</li>
<li>结束之后，这个流将不会再发出别的值</li>
</ul>
<p>一个流也可以报错（error out）：</p>
<ul>
<li>流带着一个错误结束了他的生命周期</li>
<li>当错误被抛出之后，这个流将不会再发出别的值</li>
</ul>
<p>注意 <strong>完成</strong> 和 <strong>报错</strong> 是互斥的：</p>
<ul>
<li>当流完成之后，他不能再报错</li>
<li>当流报错之后，他不能再完成</li>
</ul>
<p>同样需要注意流没有义务去“完成”或者“报错”，这两种可能性均是可选的，但是他们中只有一种情况会出现（是不是有点像薛定谔的猫，你永远不知道一个异步请求会成功还是报错(笑)）。</p>
<p>这意味着，根据 Observable 的约定，当某个流报错之后，我们就不能再使用它了。现在，你一定在考虑一个问题——那么如何来让他从错误中恢复过来呢？</p>
<h1 id="rxjs-中的-subscribe-方法与-error-回调">RxJS 中的 subscribe 方法与 error 回调</h1>
<p>现在，我们首先来创建一个流并订阅（subscribe）他。记住 subscribe 方法接受 3 个可选的参数：</p>
<ul>
<li>一个处理成功的函数，每当流发送一个值时就会调用这个函数</li>
<li>一个处理错误的函数，只有当错误发生的时候才会调用，这个函数将会接受错误（error）本身作为参数</li>
<li>一个处理完成的函数，只有当流完成的时候才会调用</li>
</ul>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">@Component</span>(&#123;</span><br><span class="line">  <span class="attr">selector</span>: <span class="string">&#x27;home&#x27;</span>,</span><br><span class="line">  <span class="attr">templateUrl</span>: <span class="string">&#x27;./home.component.html&#x27;</span></span><br><span class="line">&#125;)</span><br><span class="line"><span class="keyword">export</span> <span class="keyword">class</span> <span class="title class_">HomeComponent</span> <span class="keyword">implements</span> <span class="title class_">OnInit</span> &#123;</span><br><span class="line"></span><br><span class="line">  <span class="title function_">constructor</span>(<span class="params"><span class="keyword">private</span> http: HttpClient</span>) &#123;&#125;</span><br><span class="line"></span><br><span class="line">  <span class="title function_">ngOnInit</span>(<span class="params"></span>) &#123;</span><br><span class="line">    <span class="keyword">const</span> http$ = <span class="variable language_">this</span>.<span class="property">http</span>.<span class="property">get</span>&lt;<span class="title class_">Course</span>[]&gt;(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">    http$.<span class="title function_">subscribe</span>(</span><br><span class="line">      <span class="function"><span class="params">res</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP response&#x27;</span>, res),</span><br><span class="line">      <span class="function"><span class="params">err</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP Error&#x27;</span>, err),</span><br><span class="line">      <span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP request completed.&#x27;</span>)</span><br><span class="line">    )</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h2 id="完成行为的举例">完成行为的举例</h2>
<p>当这个流没有报错，你可以在控制台看到：</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">HTTP response &#123; payload: Array(9) &#125;</span><br><span class="line">HTTP HTTP request completed.</span><br></pre></td></tr></table></figure>
<p>这个 HTTP 流只发送了一个值，随即结束，这意味着他没有发生错误。</p>
<p>但如果他抛出一个错误会怎么样呢？在这种情况下，我们可以在控制台中看到这样的东西：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-1.png" /></p>
<p>此时流并没有发出任何值，并且立即报错。在报错之后，他没有执行完成回调。</p>
<h2 id="subscribe-方法中的-error-回调函数的局限性">subscribe 方法中的 error 回调函数的局限性</h2>
<p>有时候给 subscribe 传递 error 回调已经满足了我们处理错误的需求，但这种错误处理的方法是有局限性的。比如我们不能从错误信息中恢复过来，也不能发送另一个备用的值（fallback value）来替代我们原先希望从后端获取的值。</p>
<h1 id="catcherror-操作符">catchError 操作符</h1>
<p>在同步编程中，我们可以使用 <code>try</code> 语句来包裹代码，用 <code>catch</code> 来获取并处理可能发生的错误。</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// 同步操作</span></span><br><span class="line">  <span class="keyword">const</span> httpResponse = <span class="title function_">getHttpResponseSync</span>(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">catch</span>(error) &#123;</span><br><span class="line">  <span class="comment">// 处理错误</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>这个机制非常强大，这样我们就可以在一个地方处理 <code>try/catch</code> 代码块中发生的任何错误了。</p>
<p>但问题在于，Javascript 中很多操作都是异步的，HTTP 请求就是其中的一个。</p>
<p>RxJS 则通过 <code>catchError</code> 操作符提供了一些类似的功能。</p>
<h2 id="catcherror-是如何工作的">catchError 是如何工作的？</h2>
<p>与其他的 RxJS 运算符一样，<code>catchError</code> 只是一个输入 Observable，然后输出 Observable 的函数。</p>
<p>每次调用 <code>catchError</code> 的时候，需要传给他一个错误处理函数（error handling function）。</p>
<p><code>catchError</code> 操作符将可能报错的 Observable 作为输入，然后开始在他输出的 Observable 中发出输入的 Observable 的值。</p>
<p>如果没有错误发生，他输出的 Observable 跟输入的 Observable 将以同样的方式工作。</p>
<h2 id="当错误发生时会怎样">当错误发生时会怎样？</h2>
<p>然而，当错误发生时，<code>catchError</code> 逻辑开始生效。<code>catchError</code> 操作符将会拿到这个错误，并将其传递给错误处理函数。</p>
<p>这个函数需要返回一个 Observable，他返回的 Observable 将会代替出错的流。</p>
<p>显然根据 Observable 约定，我们不能在使用已经出错的输入 <code>catchError</code> 的那个流。</p>
<p>错误处理函数返回的替代的 Observable 将会随即被订阅（subscribe）并且它发出的值将会代替已经报错的输入的 Observable。</p>
<h1 id="捕获并替代策略the-catch-and-replace-strategy">捕获并替代策略（The Catch and Replace Strategy）</h1>
<p>来看一个 <code>catchError</code> 用来提供替代的 Observable 并发出备用值的例子：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="variable language_">this</span>.<span class="property">http</span>.<span class="property">get</span>&lt;<span class="title class_">Course</span>[]&gt;(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">http$</span><br><span class="line">  .<span class="title function_">pipe</span>(</span><br><span class="line">    <span class="title function_">catchError</span>(<span class="function"><span class="params">err</span> =&gt;</span> <span class="title function_">of</span>([]))</span><br><span class="line">  )</span><br><span class="line">  .<span class="title function_">subscribe</span>(</span><br><span class="line">    <span class="function"><span class="params">res</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP response&#x27;</span>, res),</span><br><span class="line">    <span class="function"><span class="params">err</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP Error&#x27;</span>, err),</span><br><span class="line">    <span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP request completed.&#x27;</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p>我们可以将「捕获并替代策略」分解如下：</p>
<ul>
<li>传递给 <code>catchError</code> 操作符一个错误处理函数</li>
<li>这个错误处理函数并不会立即调用，通常也不会调用</li>
<li>只有输入 <code>catchError</code> 的 Observable 发生错误时，才会调用错误处理函数</li>
<li>如果输入的流发生错误，错误处理函数将会返回一个用 <code>of([])</code> 构造的 Observable</li>
<li>这个 <code>of()</code> 函数只会返回一个值（<code>[]</code>），然后完成</li>
<li>错误处理函数返回的恢复 Observable（<code>of([])</code>）将会被 <code>catchError</code> 操作符订阅（subscribe）</li>
<li><code>catchError</code> 将会把恢复 Observable 的值作为替代值发出</li>
</ul>
<p>最终，<code>http$</code> Observable 将不会报错，我们可以在控制台看到：</p>
<figure class="highlight plaintext"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">HTTP response []</span><br><span class="line">HTTP request completed.</span><br></pre></td></tr></table></figure>
<p>我们可以看到，<code>subscribe()</code> 中的错误处理回调不再被调用，而是发生了下面的操作：</p>
<ul>
<li>一个空数组 <code>[]</code> 被发出</li>
<li><code>http$</code> Observable 随即结束</li>
</ul>
<p>尽管最初的 <code>https$</code> 确实报错了，但替代的 Observable 为 <code>http$</code> 的订阅者（subscriber）提供了一个默认的备用值（<code>[]</code>）。</p>
<p>注意我们也可以在返回替代的 Observable 之前做一些其他的错误处理。</p>
<p>这就是「捕获并替代策略」，接下来我们看看如何使用 <code>catchError</code> 来重新抛出一个错误，而不是提供替代的值。</p>
<h1 id="捕获并重抛策略the-catch-and-rethrow-strategy">捕获并重抛策略（The Catch and Rethrow Strategy）</h1>
<p>注意上面我们通过 <code>catchError</code> 提供的替代 Observable 也可能会报错——就像其他任何 Observable 一样。</p>
<p>此时，错误将会被广播给 <code>catchError</code> 输出的 Observable 的订阅者。</p>
<p>这种错误广播的行为给了我们一种在本地处理错误之后，重新抛出被 <code>catchError</code> 捕获的错误的机制。我们可以这样搞：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="variable language_">this</span>.<span class="property">http</span>.<span class="property">get</span>&lt;<span class="title class_">Course</span>[]&gt;(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">http$</span><br><span class="line">  .<span class="title function_">pipe</span>(</span><br><span class="line">    <span class="title function_">catchError</span>(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;Handling error locally and rethrowing it...&#x27;</span>, err)</span><br><span class="line">      <span class="keyword">return</span> <span class="title function_">throwError</span>(err)</span><br><span class="line">    &#125;)</span><br><span class="line">  )</span><br><span class="line">  .<span class="title function_">subscribe</span>(</span><br><span class="line">    <span class="function"><span class="params">res</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP response&#x27;</span>, res),</span><br><span class="line">    <span class="function"><span class="params">err</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP Error&#x27;</span>, err),</span><br><span class="line">    <span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP request completed.&#x27;</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<h2 id="拆解捕获并重抛策略">拆解捕获并重抛策略</h2>
<p>来一步步拆解这个「捕获并重抛策略」：</p>
<ul>
<li>像之前一样，我们正在捕获一个错误，并且返回一个替代的 Observable</li>
<li>但这次，我们在 <code>catchError</code> 函数中对这个错误进行本地处理，而不是提供一个像 <code>[]</code> 这样的替代值</li>
<li>在这个案例中，我们只是简单地在控制台输出错误，但是我们也可以增加任何我们需要的错误处理逻辑，比如向用户展示错误信息等</li>
<li><code>throwError</code> 创建了一个不会发出任何值的 Observable，并且会立即报出与 <code>catchError</code> 捕获的错误一样的错</li>
<li>这意味着 <code>catchError</code> 输出的 Observable 也会报与输入的 Observable 一样的错</li>
<li>这意味着我们终于成功地将 <code>catchError</code> 输入的 Observable 的最初的报错 <strong>重新抛给</strong> 输出的 Observable</li>
</ul>
<p>我们可以在控制台得到：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-2.png" /></p>
<h1 id="在-observable-链条中使用多次-catcherror">在 Observable 链条中使用多次 catchError</h1>
<p>注意我们可以在 Observable 链条中的不同节点根据需要多次使用 catchError，他们可以使用不同的策略。</p>
<p>比如我们可以在 Observable 链条上游中捕获错误，处理并且重抛他，然后在下游捕获同样的错误（这次我们提供一个替代的值，不再重抛他）：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="variable language_">this</span>.<span class="property">http</span>.<span class="property">get</span>&lt;<span class="title class_">Course</span>[]&gt;(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">http$</span><br><span class="line">  .<span class="title function_">pipe</span>(</span><br><span class="line">    <span class="title function_">map</span>(<span class="function"><span class="params">res</span> =&gt;</span> res[<span class="string">&#x27;payload&#x27;</span>]),</span><br><span class="line">    <span class="title function_">catchError</span>(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;Handling error locally and rethrowing it...&#x27;</span>, err)</span><br><span class="line">      <span class="keyword">return</span> <span class="title function_">throwError</span>(err)</span><br><span class="line">    &#125;),</span><br><span class="line">    <span class="title function_">catchError</span>(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;caught rethrown error, providing fallback value&#x27;</span>)</span><br><span class="line">      <span class="keyword">return</span> <span class="title function_">of</span>([])</span><br><span class="line">    &#125;)</span><br><span class="line">  )</span><br><span class="line">  .<span class="title function_">subscribe</span>(</span><br><span class="line">    <span class="function"><span class="params">res</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP response&#x27;</span>, res),</span><br><span class="line">    <span class="function"><span class="params">err</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP Error&#x27;</span>, err),</span><br><span class="line">    <span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP request completed.&#x27;</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-3.png" /></p>
<p>我们可以看到，错误事实上最开始被重抛了，但错误并没有到达 subscribe 的错误处理函数，而是发出了 <code>[]</code> 这个替代值。</p>
<h1 id="finalize-操作符">Finalize 操作符</h1>
<p>除了错误处理中的 <code>catch</code> 代码块之外，同步 Javascript 语法还提供了 <code>finally</code> 代码块来包裹一定会被执行的代码。</p>
<p><code>finally</code> 代码块在释放昂贵资源的时候特别有用，比如关闭网络请求或释放内存。</p>
<p>与 <code>catch</code> 代码块中的代码不同，<code>finally</code> 代码块中的的执行不受报错的影响。</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// 同步操作</span></span><br><span class="line">  <span class="keyword">const</span> httpResponse =  <span class="title function_">getHttpResponseSync</span>(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">catch</span> &#123;</span><br><span class="line">  <span class="comment">// 处理错误，只有当错误发生的时候才会执行</span></span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">finally</span> &#123;</span><br><span class="line">  <span class="comment">// 不管什么情况下都会执行</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>RxJS 也提供了像 <code>finally</code> 一样功能的操作符——<code>finalize</code> 操作符。</p>
<blockquote>
<p>由于是 <code>finally</code> 是保留字，因此不能使用。</p>
</blockquote>
<h2 id="finalize-操作符的例子">Finalize 操作符的例子</h2>
<p>就像 <code>catchError</code> 操作符一样，为了让不同的资源正确释放，我们可以在 Observable 链条中的不同位置添加多个 <code>finalize</code>：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="variable language_">this</span>.<span class="property">http</span>.<span class="property">get</span>&lt;<span class="title class_">Course</span>[]&gt;(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">http$</span><br><span class="line">  .<span class="title function_">pipe</span>(</span><br><span class="line">    <span class="title function_">map</span>(<span class="function"><span class="params">res</span> =&gt;</span> res[<span class="string">&#x27;payload&#x27;</span>]),</span><br><span class="line">    <span class="title function_">catchError</span>(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;caught mapping error and rethrowing&#x27;</span>, err)</span><br><span class="line">      <span class="keyword">return</span> <span class="title function_">throwError</span>(err)</span><br><span class="line">    &#125;),</span><br><span class="line">    <span class="title function_">finalize</span>(<span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;first finalize() block executed&#x27;</span>)),</span><br><span class="line">    <span class="title function_">catchError</span>(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;caught rethrown error, providing fallback value&#x27;</span>)</span><br><span class="line">      <span class="keyword">return</span> <span class="title function_">of</span>([])</span><br><span class="line">    &#125;),</span><br><span class="line">    <span class="title function_">finalize</span>(<span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;second finalize() block executed&#x27;</span>))</span><br><span class="line">  )</span><br><span class="line">  .<span class="title function_">subscribe</span>(</span><br><span class="line">    <span class="function"><span class="params">res</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP response&#x27;</span>, res),</span><br><span class="line">    <span class="function"><span class="params">err</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP Error&#x27;</span>, err),</span><br><span class="line">    <span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP request completed.&#x27;</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-4.png" /></p>
<p>注意 <code>finalize</code> 代码块在 subscribe 成功回调和完成回调之后执行</p>
<h1 id="重试策略the-retry-strategy">重试策略（The Retry Strategy）</h1>
<p>除了重抛错误与提供备用值以外，我们还可以重试已经报错的 Observable。</p>
<p>我们知道，一旦流报错，我们不能再恢复他，但我们可以重新从流的源头订阅一次，并创建一个新的流。</p>
<p>它是这样工作的：</p>
<ul>
<li>我们拿到一个输入的 Observable，然后订阅（subscribe）他，创建一个新的流</li>
<li>如果流没有报错，我们让他的结果在输出的时候展现</li>
<li>但如果流报错了，我们需要去重新订阅这个输入的 Observable，然后创建一个新的流</li>
</ul>
<h2 id="什么时候重试">什么时候重试？</h2>
<p>一个大问题是，我们什么时候重新订阅这个输入的 Observable，然后重新执行？</p>
<ul>
<li>马上重试？</li>
<li>等一小会儿，期待着这个问题被解决，然后再重试？</li>
<li>只重试限定的次数，然后报错？</li>
</ul>
<p>为了解决这些问题，我们需要一个辅助的 Observable，我们叫他「通知者」（Notifier Observable），他会决定什么时候重试。</p>
<p>作为整个「重试策略」的核心 <code>retryWhen</code> 将会使用这个「通知者」。</p>
<h1 id="rxjs-retrywhen-操作符的子弹图">RxJS retryWhen 操作符的子弹图</h1>
<p>为了理解 <code>retryWhen</code> Observable 的工作机制，我们可以看看他的子弹图：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-5.png" /></p>
<p>注意被重试的 Observable 是第二条线的 Observable 1-2，而不是第一条线的 Observable。</p>
<p>第一条线的发出 r-r 值的 Observable 是「通知者」，他会决定什么时候重试。</p>
<h2 id="拆解-retrywhen-是如何工作的">拆解 retryWhen 是如何工作的</h2>
<ul>
<li>Observable 1-2 被订阅，然后他的值被立即反射在 <code>retryWhen</code> 的输出 Observable 中</li>
<li>甚至在 Observable 1-2 结束之后，他仍然可以被重试</li>
<li>订阅者在 Observable 1-2 结束之后发出值 <code>r</code></li>
<li>订阅者发出的值可以是任何形式的（在这里就是 <code>r</code>）</li>
<li>重要的是 <code>r</code> 发出的时机，因为这就是 Observable 1-2 重试的时机</li>
<li>Observable 1-2 被 <code>retryWhen</code> 重新订阅，他的值又会被重新反射到 <code>retryWhen</code> 的输出 Observable 中</li>
<li>然后，订阅者最终还是结束了</li>
<li>在这个时候，正在进行中的 Observable 1-2 重试也被提早结束，意味着只发出了 1，而不会发出 2</li>
</ul>
<p>我们可以看到，<code>retryWhen</code> 只是在观察着发出值的时候重试输入的 Observable。</p>
<p>既然我们理解了 <code>retryWhen</code> 是如何工作的，我们现在来创建一个「通知者」</p>
<h1 id="创建一个通知者notification-observable">创建一个通知者（Notification Observable）</h1>
<p>我们需要在传递给 <code>retryWhen</code> 操作符的函数中直接创建一个通知者。这个函数将一个 Errors Observable（发出输入的 Observable 的错误的 Observable）作为参数。</p>
<p>然后通过订阅这个 Errors Observable，我们可以准确地知道什么时候发生了错误。我们现在来看看如何实施一个「立即重试策略」</p>
<h1 id="立即重试策略immediate-retry-strategy">立即重试策略（Immediate Retry Strategy）</h1>
<p>为了在错误发生之后立即重试，我们只需要返回这个 Errors Observable 即可。</p>
<p>在这个案例中，我们使用 <code>tap</code> 操作符来打 log，因此 Errors Observable 还是不变的：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="variable language_">this</span>.<span class="property">http</span>.<span class="property">get</span>&lt;<span class="title class_">Course</span>[]&gt;(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">http$</span><br><span class="line">  .<span class="title function_">pipe</span>(</span><br><span class="line">    <span class="title function_">tap</span>(<span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&quot;HTTP request executed&quot;</span>)),</span><br><span class="line">    <span class="title function_">map</span>(<span class="function"><span class="params">res</span> =&gt;</span> <span class="title class_">Object</span>.<span class="title function_">values</span>(res[<span class="string">&#x27;payload&#x27;</span>])),</span><br><span class="line">    <span class="title function_">shareReplay</span>(),</span><br><span class="line">    <span class="title function_">retryWhen</span>(<span class="function"><span class="params">errors</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="keyword">return</span> errors</span><br><span class="line">        .<span class="title function_">pipe</span>(</span><br><span class="line">          <span class="title function_">tap</span>(<span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;retrying...&#x27;</span>))</span><br><span class="line">        )</span><br><span class="line">    &#125;)</span><br><span class="line">  )</span><br><span class="line">  .<span class="title function_">subscribe</span>(</span><br><span class="line">    <span class="function"><span class="params">res</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP response&#x27;</span>, res),</span><br><span class="line">    <span class="function"><span class="params">err</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP Error&#x27;</span>, err),</span><br><span class="line">    <span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP request completed.&#x27;</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p>我们从 <code>retryWhen</code> 函数返回的 Observable 就是「通知者」（Notification Observable）。</p>
<p>他发出的值并不重要，重要的是只有他发出的时机，因为这就是重试的时机。</p>
<h2 id="立即重试策略的控制台输出内容">立即重试策略的控制台输出内容</h2>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-6.png" /></p>
<p>我们可以看到，HTTP 请求最开始错误了，但是后来尝试了一次，并且第二次的请求成功了。</p>
<p>可以看看两次尝试之间的延迟：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-7.png" /></p>
<h1 id="延迟重试策略delayed-retry-strategy">延迟重试策略（Delayed Retry Strategy）</h1>
<p>让我们来实施另一个错误恢复策略，比如在错误发生之后等待 2 秒再重试。</p>
<p>这个策略在一些从一些特定的错误（比如服务器拥塞导致的请求失败）上恢复的时候特别有效。</p>
<p>在某些错误间歇性发生的案例中，我们可以简单地在一小段延迟之后重试，然后第二次请求可能就没问题了。</p>
<h1 id="计时器timer-observable创建函数">计时器（Timer Observable）创建函数</h1>
<p>为了实施延迟重试策略，我们需要创建一个错误发生之后 2 秒再发出值的通知者。</p>
<p>接下来我们来尝试用 <code>timer</code> 来创建一个通知者，这个 <code>timer</code> 函数接受两个值：</p>
<ul>
<li>一个在第一个值发出之前的初始延迟</li>
<li>一个我们希望周期性发出值时的周期性延迟</li>
</ul>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-8.png" /></p>
<p>我们可以看到，第一个值 0 在 3 秒之后才发出，然后每隔 1 秒发出一个值。</p>
<p>注意第二个参数是可选的，比如在我们希望在只发出一个值 0 之后就结束。</p>
<p>接下来我们来看看如何如何结合 <code>retryWhen</code> 和 <code>delayWhen</code> 操作符。</p>
<h1 id="delaywhen-操作符">delayWhen 操作符</h1>
<p>一件很重要的事情就是，定义通知者的函数只会被调用一次，因此我们只有一次机会来定义这个确定何时重试的通知者。</p>
<p>我们将要获取 Errors Observable，然后应用在 <code>delayWhen</code> 操作符上来定义通知者。</p>
<p>来在这张子弹图上想一想，源 Observable a-b-c 是 Errors Observable，会随着时间发出失败的 HTTP 错误：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-9.png" /></p>
<h2 id="delaywhen-操作符的拆解">delayWhen 操作符的拆解</h2>
<p>我们通过这张图来学习一下：</p>
<ul>
<li>输入的 Errors Observable 的每个值都会被延迟之后展示在输出 Observable 中</li>
<li>每个值的延迟可以不同，并且将会被用非常灵活的方式创建</li>
<li>为了确定延迟，我们将会每个输入的 Errors Observable 的值调用传递给 <code>delayWhen</code> 的函数（也叫作持续时间选择函数，duration selector function））</li>
<li>这个函数将会发出一个将会决定每个值发出之后的延迟</li>
<li>a-b-c 中的每一个值都有自己的持续时间选择器（duration selector Observable），他最终会发出一个值（可以是任何值），然后结束</li>
<li>当三个持续时间选择器中的每个发出值的时候，对应的输入值 a-b-c 就会在最后的输出中展示</li>
<li>注意值 <code>b</code> 在 <code>c</code> 之后出现，这是很正常的</li>
<li>因为 <code>b</code> 持续时间选择器在 <code>c</code> 持续时间选择器之后发出值</li>
</ul>
<h2 id="实施延迟重试策略">实施延迟重试策略</h2>
<p>让我们现在来把这些都放到一起，看看我们怎样按顺序在 2 秒后重试每一个发生错误的 HTTP 请求。</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="variable language_">this</span>.<span class="property">http</span>.<span class="property">get</span>&lt;<span class="title class_">Course</span>[]&gt;(<span class="string">&#x27;/api/courses&#x27;</span>)</span><br><span class="line">http$</span><br><span class="line">  .<span class="title function_">pipe</span>(</span><br><span class="line">    <span class="title function_">tap</span>(<span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&quot;HTTP request executed&quot;</span>)),</span><br><span class="line">    <span class="title function_">map</span>(<span class="function"><span class="params">res</span> =&gt;</span> <span class="title class_">Object</span>.<span class="title function_">values</span>(res[<span class="string">&#x27;payload&#x27;</span>])),</span><br><span class="line">    <span class="title function_">shareReplay</span>(),</span><br><span class="line">    <span class="title function_">retryWhen</span>(<span class="function"><span class="params">errors</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="keyword">return</span> errors</span><br><span class="line">        .<span class="title function_">pipe</span>(</span><br><span class="line">          <span class="title function_">delayWhen</span>(<span class="function">() =&gt;</span> <span class="title function_">timer</span>(<span class="number">2000</span>)),</span><br><span class="line">          <span class="title function_">tap</span>(<span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;retrying...&#x27;</span>)),</span><br><span class="line">        )</span><br><span class="line">    &#125;)</span><br><span class="line">  )</span><br><span class="line">  .<span class="title function_">subscribe</span>(</span><br><span class="line">    <span class="function"><span class="params">res</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP response&#x27;</span>, res),</span><br><span class="line">    <span class="function"><span class="params">err</span> =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP Error&#x27;</span>, err),</span><br><span class="line">    <span class="function">() =&gt;</span> <span class="variable language_">console</span>.<span class="title function_">log</span>(<span class="string">&#x27;HTTP request completed.&#x27;</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p>来拆解一下：</p>
<ul>
<li>传给 <code>retryWhen</code> 的函数只会调用一次</li>
<li>我们在那个函数中返回一个 Observable，他在任何需要重试的时候就会发送值</li>
<li>每当出现一个错误，<code>delayWhen</code> 操作符就会通过调用 <code>timer</code> 函数来创建一个持续时间选择器（duration selector Observable）</li>
<li>这个持续时间选择器将会在 2 秒后发出 0，然后结束</li>
<li>每当这发生的时候，delayWhen Observable 就会知道输入的错误的延迟已经结束了</li>
<li>只有当延迟结束之后，错误才会在通知者的输出中出现</li>
<li>一旦通知者中的值发出，<code>retryWhen</code> 操作符就会执行重试</li>
</ul>
<h2 id="延迟策略的控制台输出内容">延迟策略的控制台输出内容</h2>
<p>下面是某个 HTTP 请求，重试了 5 次，并且其中 4 次报错的情况：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-10.png" /></p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-11.png" /></p>
<p>可以看到与预期一样，重试在错误发生 2 秒之后才会进行。</p>

    </div>

    
    
    

    <footer class="post-footer">
          <div class="post-tags">
              <a href="/hais-notebook/tags/%E5%85%A5%E9%97%A8/" rel="tag"># 入门</a>
              <a href="/hais-notebook/tags/RxJS/" rel="tag"># RxJS</a>
          </div>

        

          <div class="post-nav">
            <div class="post-nav-item">
                <a href="/hais-notebook/2021/03/03/Tools-Webpack-Core/" rel="prev" title="Webpack 核心原理">
                  <i class="fa fa-chevron-left"></i> Webpack 核心原理
                </a>
            </div>
            <div class="post-nav-item">
                <a href="/hais-notebook/2021/03/14/Tools-Docker/" rel="next" title="Docker">
                  Docker <i class="fa fa-chevron-right"></i>
                </a>
            </div>
          </div>
    </footer>
  </article>
</div>






</div>
  </main>

  <footer class="footer">
    <div class="footer-inner">


<div class="copyright">
  &copy; 
  <span itemprop="copyrightYear">2022</span>
  <span class="with-love">
    <i class="fa fa-heart"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Harvey Zhang</span>
</div>
  <div class="powered-by">由 <a href="https://hexo.io/" rel="noopener" target="_blank">Hexo</a> & <a href="https://theme-next.js.org/" rel="noopener" target="_blank">NexT.Gemini</a> 强力驱动
  </div>

    </div>
  </footer>

  
  <script src="/hais-notebook/lib/animejs/lib/anime.min.js" integrity="sha256-XL2inqUJaslATFnHdJOi9GfQ60on8Wx1C2H8DYiN1xY=" crossorigin="anonymous"></script>
<script src="/hais-notebook/js/comments.js"></script><script src="/hais-notebook/js/utils.js"></script><script src="/hais-notebook/js/next-boot.js"></script>

  
<script src="/hais-notebook/lib/hexo-generator-searchdb/dist/search.js" integrity="sha256-vXZMYLEqsROAXkEw93GGIvaB2ab+QW6w3+1ahD9nXXA=" crossorigin="anonymous"></script>
<script src="/hais-notebook/js/third-party/search/local-search.js"></script>





  




  

  <script class="next-config" data-name="enableMath" type="application/json">false</script><script class="next-config" data-name="mathjax" type="application/json">{"enable":true,"tags":"none","js":{"url":"/hais-notebook/lib/mathjax/es5/tex-mml-chtml.js","integrity":"sha256-hlC2uSQYTmPsrzGZTEQEg9PZ1a/+SV6VBCTclohf2og="}}</script>
<script src="/hais-notebook/js/third-party/math/mathjax.js"></script>



</body>
</html>
