<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=2">
<meta name="theme-color" content="#222">
<meta name="generator" content="Hexo 4.2.0">
  <link rel="apple-touch-icon" sizes="180x180" href="/hais-notebook/images/apple-touch-icon.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/hais-notebook/images/favicon-32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/hais-notebook/images/favicon-16x16.png">

<link rel="stylesheet" href="/hais-notebook/css/main.css">


<link rel="stylesheet" href="/hais-notebook/lib/font-awesome/css/font-awesome.min.css">


<script id="hexo-configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    hostname: new URL('https://hyuain.github.io/hais-notebook').hostname,
    root: '/hais-notebook/',
    scheme: 'Gemini',
    version: '7.7.0',
    exturl: false,
    sidebar: {"position":"left","display":"post","padding":18,"offset":12,"onmobile":false},
    copycode: {"enable":false,"show_result":false,"style":null},
    back2top: {"enable":true,"sidebar":false,"scrollpercent":false},
    bookmark: {"enable":false,"color":"#222","save":"auto"},
    fancybox: false,
    mediumzoom: false,
    lazyload: false,
    pangu: false,
    comments: {"style":"tabs","active":null,"storage":true,"lazyload":false,"nav":null},
    algolia: {
      appID: 'W0QZQNNH7N',
      apiKey: '00189c8d102508ea71e94422b5f129fd',
      indexName: 'hais-notebook',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    },
    localsearch: {"enable":true,"trigger":"auto","top_n_per_article":1,"unescape":false,"preload":false},
    path: 'search.xml',
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}}
  };
</script>

  <meta name="description" content="本文是 RxJS Error Handling 的翻译。主要介绍了 catchError、throwError、Finalize、retryWhen、delayWhen 等操作符，以及捕获并替代策略、捕获并重抛策略、重试策略等错误处理方法。">
<meta property="og:type" content="article">
<meta property="og:title" content="翻译：RxJS 中的错误处理">
<meta property="og:url" content="https://hyuain.github.io/hais-notebook/2021/03/03/Tools-RxJS-ErrorHandling/index.html">
<meta property="og:site_name" content="Hais Notebook">
<meta property="og:description" content="本文是 RxJS Error Handling 的翻译。主要介绍了 catchError、throwError、Finalize、retryWhen、delayWhen 等操作符，以及捕获并替代策略、捕获并重抛策略、重试策略等错误处理方法。">
<meta property="og:locale" content="zh_CN">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-1.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-2.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-3.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-4.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-5.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-6.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-7.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-8.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-9.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-10.png">
<meta property="og:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-11.png">
<meta property="article:published_time" content="2021-03-03T22:47:21.000Z">
<meta property="article:modified_time" content="2021-05-13T08:31:16.740Z">
<meta property="article:author" content="Harvey Zhang">
<meta property="article:tag" content="入门">
<meta name="twitter:card" content="summary">
<meta name="twitter:image" content="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-1.png">

<link rel="canonical" href="https://hyuain.github.io/hais-notebook/2021/03/03/Tools-RxJS-ErrorHandling/">


<script id="page-configurations">
  // https://hexo.io/docs/variables.html
  CONFIG.page = {
    sidebar: "",
    isHome: false,
    isPost: true
  };
</script>

  <title>翻译：RxJS 中的错误处理 | Hais Notebook</title>
  






  <noscript>
  <style>
  .use-motion .brand,
  .use-motion .menu-item,
  .sidebar-inner,
  .use-motion .post-block,
  .use-motion .pagination,
  .use-motion .comments,
  .use-motion .post-header,
  .use-motion .post-body,
  .use-motion .collection-header { opacity: initial; }

  .use-motion .site-title,
  .use-motion .site-subtitle {
    opacity: initial;
    top: initial;
  }

  .use-motion .logo-line-before i { left: initial; }
  .use-motion .logo-line-after i { right: initial; }
  </style>
</noscript>

</head>

<body itemscope itemtype="http://schema.org/WebPage">
  <div class="container use-motion">
    <div class="headband"></div>

    <header class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-container">
  <div class="site-meta">

    <div>
      <a href="/hais-notebook/" class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">Hais Notebook</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
  </div>

  <div class="site-nav-toggle">
    <div class="toggle" aria-label="切换导航栏">
      <span class="toggle-line toggle-line-first"></span>
      <span class="toggle-line toggle-line-middle"></span>
      <span class="toggle-line toggle-line-last"></span>
    </div>
  </div>
</div>


<nav class="site-nav">
  
  <ul id="menu" class="menu">
        <li class="menu-item menu-item-home">

    <a href="/hais-notebook/" rel="section"><i class="fa fa-fw fa-home"></i>首页</a>

  </li>
        <li class="menu-item menu-item-tags">

    <a href="/hais-notebook/tags/" rel="section"><i class="fa fa-fw fa-tags"></i>标签</a>

  </li>
        <li class="menu-item menu-item-categories">

    <a href="/hais-notebook/categories/" rel="section"><i class="fa fa-fw fa-th"></i>分类</a>

  </li>
        <li class="menu-item menu-item-archives">

    <a href="/hais-notebook/archives/" rel="section"><i class="fa fa-fw fa-archive"></i>归档</a>

  </li>
      <li class="menu-item menu-item-search">
        <a role="button" class="popup-trigger"><i class="fa fa-search fa-fw"></i>搜索
        </a>
      </li>
  </ul>

</nav>
  <div class="site-search">
    <div class="popup search-popup">
    <div class="search-header">
  <span class="search-icon">
    <i class="fa fa-search"></i>
  </span>
  <div class="search-input-container">
    <input autocomplete="off" autocorrect="off" autocapitalize="none"
           placeholder="搜索..." spellcheck="false"
           type="text" id="search-input">
  </div>
  <span class="popup-btn-close">
    <i class="fa fa-times-circle"></i>
  </span>
</div>
<div id="search-result"></div>

</div>
<div class="search-pop-overlay"></div>

  </div>
</div>
    </header>

    
  <div class="back-to-top">
    <i class="fa fa-arrow-up"></i>
    <span>0%</span>
  </div>


    <main class="main">
      <div class="main-inner">
        <div class="content-wrap">
          

          <div class="content">
            

  <div class="posts-expand">
      
  
  
  <article itemscope itemtype="http://schema.org/Article" class="post-block " lang="zh-CN">
    <link itemprop="mainEntityOfPage" href="https://hyuain.github.io/hais-notebook/2021/03/03/Tools-RxJS-ErrorHandling/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="image" content="/hais-notebook/images/avatar.gif">
      <meta itemprop="name" content="Harvey Zhang">
      <meta itemprop="description" content="小海的笔记本">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="Hais Notebook">
    </span>
      <header class="post-header">
        <h1 class="post-title" itemprop="name headline">
          翻译：RxJS 中的错误处理
        </h1>

        <div class="post-meta">
            <span class="post-meta-item">
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              <span class="post-meta-item-text">发表于</span>

              <time title="创建时间：2021-03-03 22:47:21" itemprop="dateCreated datePublished" datetime="2021-03-03T22:47:21+00:00">2021-03-03</time>
            </span>
              <span class="post-meta-item">
                <span class="post-meta-item-icon">
                  <i class="fa fa-calendar-check-o"></i>
                </span>
                <span class="post-meta-item-text">更新于</span>
                <time title="修改时间：2021-05-13 08:31:16" itemprop="dateModified" datetime="2021-05-13T08:31:16+00:00">2021-05-13</time>
              </span>
            <span class="post-meta-item">
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
              <span class="post-meta-item-text">分类于</span>
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/hais-notebook/categories/%E5%B7%A5%E5%85%B7/" itemprop="url" rel="index">
                    <span itemprop="name">工具</span>
                  </a>
                </span>
                  ，
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/hais-notebook/categories/%E5%B7%A5%E5%85%B7/RxJS/" itemprop="url" rel="index">
                    <span itemprop="name">RxJS</span>
                  </a>
                </span>
            </span>

          

        </div>
      </header>

    
    
    
    <div class="post-body" itemprop="articleBody">

      
        <p>本文是 <a href="https://blog.angular-university.io/rxjs-error-handling/" target="_blank" rel="noopener">RxJS Error Handling</a> 的翻译。<br>主要介绍了 catchError、throwError、Finalize、retryWhen、delayWhen 等操作符，以及捕获并替代策略、捕获并重抛策略、重试策略等错误处理方法。</p>
<a id="more"></a>
<h1 id="Observable-中的约定与错误处理"><a href="#Observable-中的约定与错误处理" class="headerlink" title="Observable 中的约定与错误处理"></a>Observable 中的约定与错误处理</h1><p>为了理解 RxJS 中的错误处理，我们需要先知道尽管数据流可以不发送值，也可以发送多个值，但 <strong>一个数据流（stream）只能输出一次错误</strong>。我们做出如此的约定，因为在实践中我们所观察（observe）的所有的流都是这样工作的，比如可能发生错误的网络请求等。</p>
<p>一个流可以顺利完成（complete），这意味着：</p>
<ul>
<li>一个流结束了他的生命周期，在此期间没有发生任何错误</li>
<li>结束之后，这个流将不会再发出别的值</li>
</ul>
<p>一个流也可以报错（error out）：</p>
<ul>
<li>流带着一个错误结束了他的生命周期</li>
<li>当错误被抛出之后，这个流将不会再发出别的值</li>
</ul>
<p>注意 <strong>完成</strong> 和 <strong>报错</strong> 是互斥的：</p>
<ul>
<li>当流完成之后，他不能再报错</li>
<li>当流报错之后，他不能再完成</li>
</ul>
<p>同样需要注意流没有义务去“完成”或者“报错”，这两种可能性均是可选的，但是他们中只有一种情况会出现（是不是有点像薛定谔的猫，你永远不知道一个异步请求会成功还是报错(笑)）。</p>
<p>这意味着，根据 Observable 的约定，当某个流报错之后，我们就不能再使用它了。现在，你一定在考虑一个问题——那么如何来让他从错误中恢复过来呢？</p>
<h1 id="RxJS-中的-subscribe-方法与-error-回调"><a href="#RxJS-中的-subscribe-方法与-error-回调" class="headerlink" title="RxJS 中的 subscribe 方法与 error 回调"></a>RxJS 中的 subscribe 方法与 error 回调</h1><p>现在，我们首先来创建一个流并订阅（subscribe）他。记住 subscribe 方法接受 3 个可选的参数：</p>
<ul>
<li>一个处理成功的函数，每当流发送一个值时就会调用这个函数</li>
<li>一个处理错误的函数，只有当错误发生的时候才会调用，这个函数将会接受错误（error）本身作为参数</li>
<li>一个处理完成的函数，只有当流完成的时候才会调用</li>
</ul>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br></pre></td><td class="code"><pre><span class="line"><span class="meta">@Component</span>(&#123;</span><br><span class="line">  selector: <span class="string">'home'</span>,</span><br><span class="line">  templateUrl: <span class="string">'./home.component.html'</span></span><br><span class="line">&#125;)</span><br><span class="line"><span class="keyword">export</span> <span class="keyword">class</span> HomeComponent <span class="keyword">implements</span> OnInit &#123;</span><br><span class="line"></span><br><span class="line">  <span class="keyword">constructor</span>(<span class="params"><span class="keyword">private</span> http: HttpClient</span>) &#123;&#125;</span><br><span class="line"></span><br><span class="line">  ngOnInit() &#123;</span><br><span class="line">    <span class="keyword">const</span> http$ = <span class="keyword">this</span>.http.get&lt;Course[]&gt;(<span class="string">'/api/courses'</span>)</span><br><span class="line">    http$.subscribe(</span><br><span class="line">      res =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP response'</span>, res),</span><br><span class="line">      err =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP Error'</span>, err),</span><br><span class="line">      () =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP request completed.'</span>)</span><br><span class="line">    )</span><br><span class="line">  &#125;</span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<h2 id="完成行为的举例"><a href="#完成行为的举例" class="headerlink" title="完成行为的举例"></a>完成行为的举例</h2><p>当这个流没有报错，你可以在控制台看到：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">HTTP response &#123; payload: Array(9) &#125;</span><br><span class="line">HTTP HTTP request completed.</span><br></pre></td></tr></table></figure>
<p>这个 HTTP 流只发送了一个值，随即结束，这意味着他没有发生错误。</p>
<p>但如果他抛出一个错误会怎么样呢？在这种情况下，我们可以在控制台中看到这样的东西：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-1.png" alt=""></p>
<p>此时流并没有发出任何值，并且立即报错。在报错之后，他没有执行完成回调。</p>
<h2 id="subscribe-方法中的-error-回调函数的局限性"><a href="#subscribe-方法中的-error-回调函数的局限性" class="headerlink" title="subscribe 方法中的 error 回调函数的局限性"></a>subscribe 方法中的 error 回调函数的局限性</h2><p>有时候给 subscribe 传递 error 回调已经满足了我们处理错误的需求，但这种错误处理的方法是有局限性的。比如我们不能从错误信息中恢复过来，也不能发送另一个备用的值（fallback value）来替代我们原先希望从后端获取的值。</p>
<h1 id="catchError-操作符"><a href="#catchError-操作符" class="headerlink" title="catchError 操作符"></a>catchError 操作符</h1><p>在同步编程中，我们可以使用 <code>try</code> 语句来包裹代码，用 <code>catch</code> 来获取并处理可能发生的错误。</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// 同步操作</span></span><br><span class="line">  <span class="keyword">const</span> httpResponse = getHttpResponseSync(<span class="string">'/api/courses'</span>)</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">catch</span>(error) &#123;</span><br><span class="line">  <span class="comment">// 处理错误</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>这个机制非常强大，这样我们就可以在一个地方处理 <code>try/catch</code> 代码块中发生的任何错误了。</p>
<p>但问题在于，Javascript 中很多操作都是异步的，HTTP 请求就是其中的一个。</p>
<p>RxJS 则通过 <code>catchError</code> 操作符提供了一些类似的功能。</p>
<h2 id="catchError-是如何工作的？"><a href="#catchError-是如何工作的？" class="headerlink" title="catchError 是如何工作的？"></a>catchError 是如何工作的？</h2><p>与其他的 RxJS 运算符一样，<code>catchError</code> 只是一个输入 Observable，然后输出 Observable 的函数。</p>
<p>每次调用 <code>catchError</code> 的时候，需要传给他一个错误处理函数（error handling function）。</p>
<p><code>catchError</code> 操作符将可能报错的 Observable 作为输入，然后开始在他输出的 Observable 中发出输入的 Observable 的值。</p>
<p>如果没有错误发生，他输出的 Observable 跟输入的 Observable 将以同样的方式工作。</p>
<h2 id="当错误发生时会怎样？"><a href="#当错误发生时会怎样？" class="headerlink" title="当错误发生时会怎样？"></a>当错误发生时会怎样？</h2><p>然而，当错误发生时，<code>catchError</code> 逻辑开始生效。<code>catchError</code> 操作符将会拿到这个错误，并将其传递给错误处理函数。</p>
<p>这个函数需要返回一个 Observable，他返回的 Observable 将会代替出错的流。</p>
<p>显然根据 Observable 约定，我们不能在使用已经出错的输入 <code>catchError</code> 的那个流。</p>
<p>错误处理函数返回的替代的 Observable 将会随即被订阅（subscribe）并且它发出的值将会代替已经报错的输入的 Observable。</p>
<h1 id="捕获并替代策略（The-Catch-and-Replace-Strategy）"><a href="#捕获并替代策略（The-Catch-and-Replace-Strategy）" class="headerlink" title="捕获并替代策略（The Catch and Replace Strategy）"></a>捕获并替代策略（The Catch and Replace Strategy）</h1><p>来看一个 <code>catchError</code> 用来提供替代的 Observable 并发出备用值的例子：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="keyword">this</span>.http.get&lt;Course[]&gt;(<span class="string">'/api/courses'</span>)</span><br><span class="line">http$</span><br><span class="line">  .pipe(</span><br><span class="line">    catchError(<span class="function"><span class="params">err</span> =&gt;</span> of([]))</span><br><span class="line">  )</span><br><span class="line">  .subscribe(</span><br><span class="line">    res =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP response'</span>, res),</span><br><span class="line">    err =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP Error'</span>, err),</span><br><span class="line">    () =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP request completed.'</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p>我们可以将「捕获并替代策略」分解如下：</p>
<ul>
<li>传递给 <code>catchError</code> 操作符一个错误处理函数</li>
<li>这个错误处理函数并不会立即调用，通常也不会调用</li>
<li>只有输入 <code>catchError</code> 的 Observable 发生错误时，才会调用错误处理函数</li>
<li>如果输入的流发生错误，错误处理函数将会返回一个用 <code>of([])</code> 构造的 Observable</li>
<li>这个 <code>of()</code> 函数只会返回一个值（<code>[]</code>），然后完成</li>
<li>错误处理函数返回的恢复 Observable（<code>of([])</code>）将会被 <code>catchError</code> 操作符订阅（subscribe）</li>
<li><code>catchError</code> 将会把恢复 Observable 的值作为替代值发出</li>
</ul>
<p>最终，<code>http$</code> Observable 将不会报错，我们可以在控制台看到：</p>
<figure class="highlight plain"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br></pre></td><td class="code"><pre><span class="line">HTTP response []</span><br><span class="line">HTTP request completed.</span><br></pre></td></tr></table></figure>
<p>我们可以看到，<code>subscribe()</code> 中的错误处理回调不再被调用，而是发生了下面的操作：</p>
<ul>
<li>一个空数组 <code>[]</code> 被发出</li>
<li><code>http$</code> Observable 随即结束</li>
</ul>
<p>尽管最初的 <code>https$</code> 确实报错了，但替代的 Observable 为 <code>http$</code> 的订阅者（subscriber）提供了一个默认的备用值（<code>[]</code>）。</p>
<p>注意我们也可以在返回替代的 Observable 之前做一些其他的错误处理。</p>
<p>这就是「捕获并替代策略」，接下来我们看看如何使用 <code>catchError</code> 来重新抛出一个错误，而不是提供替代的值。</p>
<h1 id="捕获并重抛策略（The-Catch-and-Rethrow-Strategy）"><a href="#捕获并重抛策略（The-Catch-and-Rethrow-Strategy）" class="headerlink" title="捕获并重抛策略（The Catch and Rethrow Strategy）"></a>捕获并重抛策略（The Catch and Rethrow Strategy）</h1><p>注意上面我们通过 <code>catchError</code> 提供的替代 Observable 也可能会报错——就像其他任何 Observable 一样。</p>
<p>此时，错误将会被广播给 <code>catchError</code> 输出的 Observable 的订阅者。</p>
<p>这种错误广播的行为给了我们一种在本地处理错误之后，重新抛出被 <code>catchError</code> 捕获的错误的机制。我们可以这样搞：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="keyword">this</span>.http.get&lt;Course[]&gt;(<span class="string">'/api/courses'</span>)</span><br><span class="line">http$</span><br><span class="line">  .pipe(</span><br><span class="line">    catchError(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="built_in">console</span>.log(<span class="string">'Handling error locally and rethrowing it...'</span>, err)</span><br><span class="line">      <span class="keyword">return</span> throwError(err)</span><br><span class="line">    &#125;)</span><br><span class="line">  )</span><br><span class="line">  .subscribe(</span><br><span class="line">    res =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP response'</span>, res),</span><br><span class="line">    err =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP Error'</span>, err),</span><br><span class="line">    () =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP request completed.'</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<h2 id="拆解捕获并重抛策略"><a href="#拆解捕获并重抛策略" class="headerlink" title="拆解捕获并重抛策略"></a>拆解捕获并重抛策略</h2><p>来一步步拆解这个「捕获并重抛策略」：</p>
<ul>
<li>像之前一样，我们正在捕获一个错误，并且返回一个替代的 Observable</li>
<li>但这次，我们在 <code>catchError</code> 函数中对这个错误进行本地处理，而不是提供一个像 <code>[]</code> 这样的替代值</li>
<li>在这个案例中，我们只是简单地在控制台输出错误，但是我们也可以增加任何我们需要的错误处理逻辑，比如向用户展示错误信息等</li>
<li><code>throwError</code> 创建了一个不会发出任何值的 Observable，并且会立即报出与 <code>catchError</code> 捕获的错误一样的错</li>
<li>这意味着 <code>catchError</code> 输出的 Observable 也会报与输入的 Observable 一样的错</li>
<li>这意味着我们终于成功地将 <code>catchError</code> 输入的 Observable 的最初的报错 <strong>重新抛给</strong> 输出的 Observable</li>
</ul>
<p>我们可以在控制台得到：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-2.png" alt=""></p>
<h1 id="在-Observable-链条中使用多次-catchError"><a href="#在-Observable-链条中使用多次-catchError" class="headerlink" title="在 Observable 链条中使用多次 catchError"></a>在 Observable 链条中使用多次 catchError</h1><p>注意我们可以在 Observable 链条中的不同节点根据需要多次使用 catchError，他们可以使用不同的策略。</p>
<p>比如我们可以在 Observable 链条上游中捕获错误，处理并且重抛他，然后在下游捕获同样的错误（这次我们提供一个替代的值，不再重抛他）：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="keyword">this</span>.http.get&lt;Course[]&gt;(<span class="string">'/api/courses'</span>)</span><br><span class="line">http$</span><br><span class="line">  .pipe(</span><br><span class="line">    map(<span class="function"><span class="params">res</span> =&gt;</span> res[<span class="string">'payload'</span>]),</span><br><span class="line">    catchError(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="built_in">console</span>.log(<span class="string">'Handling error locally and rethrowing it...'</span>, err)</span><br><span class="line">      <span class="keyword">return</span> throwError(err)</span><br><span class="line">    &#125;),</span><br><span class="line">    catchError(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="built_in">console</span>.log(<span class="string">'caught rethrown error, providing fallback value'</span>)</span><br><span class="line">      <span class="keyword">return</span> of([])</span><br><span class="line">    &#125;)</span><br><span class="line">  )</span><br><span class="line">  .subscribe(</span><br><span class="line">    res =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP response'</span>, res),</span><br><span class="line">    err =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP Error'</span>, err),</span><br><span class="line">    () =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP request completed.'</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-3.png" alt=""></p>
<p>我们可以看到，错误事实上最开始被重抛了，但错误并没有到达 subscribe 的错误处理函数，而是发出了 <code>[]</code> 这个替代值。</p>
<h1 id="Finalize-操作符"><a href="#Finalize-操作符" class="headerlink" title="Finalize 操作符"></a>Finalize 操作符</h1><p>除了错误处理中的 <code>catch</code> 代码块之外，同步 Javascript 语法还提供了 <code>finally</code> 代码块来包裹一定会被执行的代码。</p>
<p><code>finally</code> 代码块在释放昂贵资源的时候特别有用，比如关闭网络请求或释放内存。</p>
<p>与 <code>catch</code> 代码块中的代码不同，<code>finally</code> 代码块中的的执行不受报错的影响。</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">try</span> &#123;</span><br><span class="line">  <span class="comment">// 同步操作</span></span><br><span class="line">  <span class="keyword">const</span> httpResponse =  getHttpResponseSync(<span class="string">'/api/courses'</span>)</span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">catch</span> &#123;</span><br><span class="line">  <span class="comment">// 处理错误，只有当错误发生的时候才会执行</span></span><br><span class="line">&#125;</span><br><span class="line"><span class="keyword">finally</span> &#123;</span><br><span class="line">  <span class="comment">// 不管什么情况下都会执行</span></span><br><span class="line">&#125;</span><br></pre></td></tr></table></figure>
<p>RxJS 也提供了像 <code>finally</code> 一样功能的操作符——<code>finalize</code> 操作符。</p>
<blockquote>
<p>由于是 <code>finally</code> 是保留字，因此不能使用。</p>
</blockquote>
<h2 id="Finalize-操作符的例子"><a href="#Finalize-操作符的例子" class="headerlink" title="Finalize 操作符的例子"></a>Finalize 操作符的例子</h2><p>就像 <code>catchError</code> 操作符一样，为了让不同的资源正确释放，我们可以在 Observable 链条中的不同位置添加多个 <code>finalize</code>：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br><span class="line">20</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="keyword">this</span>.http.get&lt;Course[]&gt;(<span class="string">'/api/courses'</span>)</span><br><span class="line">http$</span><br><span class="line">  .pipe(</span><br><span class="line">    map(<span class="function"><span class="params">res</span> =&gt;</span> res[<span class="string">'payload'</span>]),</span><br><span class="line">    catchError(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="built_in">console</span>.log(<span class="string">'caught mapping error and rethrowing'</span>, err)</span><br><span class="line">      <span class="keyword">return</span> throwError(err)</span><br><span class="line">    &#125;),</span><br><span class="line">    finalize(<span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'first finalize() block executed'</span>)),</span><br><span class="line">    catchError(<span class="function"><span class="params">err</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="built_in">console</span>.log(<span class="string">'caught rethrown error, providing fallback value'</span>)</span><br><span class="line">      <span class="keyword">return</span> of([])</span><br><span class="line">    &#125;),</span><br><span class="line">    finalize(<span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'second finalize() block executed'</span>))</span><br><span class="line">  )</span><br><span class="line">  .subscribe(</span><br><span class="line">    res =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP response'</span>, res),</span><br><span class="line">    err =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP Error'</span>, err),</span><br><span class="line">    () =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP request completed.'</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-4.png" alt=""></p>
<p>注意 <code>finalize</code> 代码块在 subscribe 成功回调和完成回调之后执行</p>
<h1 id="重试策略（The-Retry-Strategy）"><a href="#重试策略（The-Retry-Strategy）" class="headerlink" title="重试策略（The Retry Strategy）"></a>重试策略（The Retry Strategy）</h1><p>除了重抛错误与提供备用值以外，我们还可以重试已经报错的 Observable。</p>
<p>我们知道，一旦流报错，我们不能再恢复他，但我们可以重新从流的源头订阅一次，并创建一个新的流。</p>
<p>它是这样工作的：</p>
<ul>
<li>我们拿到一个输入的 Observable，然后订阅（subscribe）他，创建一个新的流</li>
<li>如果流没有报错，我们让他的结果在输出的时候展现</li>
<li>但如果流报错了，我们需要去重新订阅这个输入的 Observable，然后创建一个新的流</li>
</ul>
<h2 id="什么时候重试？"><a href="#什么时候重试？" class="headerlink" title="什么时候重试？"></a>什么时候重试？</h2><p>一个大问题是，我们什么时候重新订阅这个输入的 Observable，然后重新执行？</p>
<ul>
<li>马上重试？</li>
<li>等一小会儿，期待着这个问题被解决，然后再重试？</li>
<li>只重试限定的次数，然后报错？</li>
</ul>
<p>为了解决这些问题，我们需要一个辅助的 Observable，我们叫他「通知者」（Notifier Observable），他会决定什么时候重试。</p>
<p>作为整个「重试策略」的核心 <code>retryWhen</code> 将会使用这个「通知者」。</p>
<h1 id="RxJS-retryWhen-操作符的子弹图"><a href="#RxJS-retryWhen-操作符的子弹图" class="headerlink" title="RxJS retryWhen 操作符的子弹图"></a>RxJS retryWhen 操作符的子弹图</h1><p>为了理解 <code>retryWhen</code> Observable 的工作机制，我们可以看看他的子弹图：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-5.png" alt=""></p>
<p>注意被重试的 Observable 是第二条线的 Observable 1-2，而不是第一条线的 Observable。</p>
<p>第一条线的发出 r-r 值的 Observable 是「通知者」，他会决定什么时候重试。</p>
<h2 id="拆解-retryWhen-是如何工作的"><a href="#拆解-retryWhen-是如何工作的" class="headerlink" title="拆解 retryWhen 是如何工作的"></a>拆解 retryWhen 是如何工作的</h2><ul>
<li>Observable 1-2 被订阅，然后他的值被立即反射在 <code>retryWhen</code> 的输出 Observable 中</li>
<li>甚至在 Observable 1-2 结束之后，他仍然可以被重试</li>
<li>订阅者在 Observable 1-2 结束之后发出值 <code>r</code></li>
<li>订阅者发出的值可以是任何形式的（在这里就是 <code>r</code>）</li>
<li>重要的是 <code>r</code> 发出的时机，因为这就是 Observable 1-2 重试的时机</li>
<li>Observable 1-2 被 <code>retryWhen</code> 重新订阅，他的值又会被重新反射到 <code>retryWhen</code> 的输出 Observable 中</li>
<li>然后，订阅者最终还是结束了</li>
<li>在这个时候，正在进行中的 Observable 1-2 重试也被提早结束，意味着只发出了 1，而不会发出 2</li>
</ul>
<p>我们可以看到，<code>retryWhen</code> 只是在观察着发出值的时候重试输入的 Observable。</p>
<p>既然我们理解了 <code>retryWhen</code> 是如何工作的，我们现在来创建一个「通知者」</p>
<h1 id="创建一个通知者（Notification-Observable）"><a href="#创建一个通知者（Notification-Observable）" class="headerlink" title="创建一个通知者（Notification Observable）"></a>创建一个通知者（Notification Observable）</h1><p>我们需要在传递给 <code>retryWhen</code> 操作符的函数中直接创建一个通知者。这个函数将一个 Errors Observable（发出输入的 Observable 的错误的 Observable）作为参数。</p>
<p>然后通过订阅这个 Errors Observable，我们可以准确地知道什么时候发生了错误。我们现在来看看如何实施一个「立即重试策略」</p>
<h1 id="立即重试策略（Immediate-Retry-Strategy）"><a href="#立即重试策略（Immediate-Retry-Strategy）" class="headerlink" title="立即重试策略（Immediate Retry Strategy）"></a>立即重试策略（Immediate Retry Strategy）</h1><p>为了在错误发生之后立即重试，我们只需要返回这个 Errors Observable 即可。</p>
<p>在这个案例中，我们使用 <code>tap</code> 操作符来打 log，因此 Errors Observable 还是不变的：</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="keyword">this</span>.http.get&lt;Course[]&gt;(<span class="string">'/api/courses'</span>)</span><br><span class="line">http$</span><br><span class="line">  .pipe(</span><br><span class="line">    tap(<span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">"HTTP request executed"</span>)),</span><br><span class="line">    map(<span class="function"><span class="params">res</span> =&gt;</span> <span class="built_in">Object</span>.values(res[<span class="string">'payload'</span>])),</span><br><span class="line">    shareReplay(),</span><br><span class="line">    retryWhen(<span class="function"><span class="params">errors</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="keyword">return</span> errors</span><br><span class="line">        .pipe(</span><br><span class="line">          tap(<span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'retrying...'</span>))</span><br><span class="line">        )</span><br><span class="line">    &#125;)</span><br><span class="line">  )</span><br><span class="line">  .subscribe(</span><br><span class="line">    res =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP response'</span>, res),</span><br><span class="line">    err =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP Error'</span>, err),</span><br><span class="line">    () =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP request completed.'</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p>我们从 <code>retryWhen</code> 函数返回的 Observable 就是「通知者」（Notification Observable）。</p>
<p>他发出的值并不重要，重要的是只有他发出的时机，因为这就是重试的时机。</p>
<h2 id="立即重试策略的控制台输出内容"><a href="#立即重试策略的控制台输出内容" class="headerlink" title="立即重试策略的控制台输出内容"></a>立即重试策略的控制台输出内容</h2><p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-6.png" alt=""></p>
<p>我们可以看到，HTTP 请求最开始错误了，但是后来尝试了一次，并且第二次的请求成功了。</p>
<p>可以看看两次尝试之间的延迟：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-7.png" alt=""></p>
<h1 id="延迟重试策略（Delayed-Retry-Strategy）"><a href="#延迟重试策略（Delayed-Retry-Strategy）" class="headerlink" title="延迟重试策略（Delayed Retry Strategy）"></a>延迟重试策略（Delayed Retry Strategy）</h1><p>让我们来实施另一个错误恢复策略，比如在错误发生之后等待 2 秒再重试。</p>
<p>这个策略在一些从一些特定的错误（比如服务器拥塞导致的请求失败）上恢复的时候特别有效。</p>
<p>在某些错误间歇性发生的案例中，我们可以简单地在一小段延迟之后重试，然后第二次请求可能就没问题了。</p>
<h1 id="计时器（Timer-Observable）创建函数"><a href="#计时器（Timer-Observable）创建函数" class="headerlink" title="计时器（Timer Observable）创建函数"></a>计时器（Timer Observable）创建函数</h1><p>为了实施延迟重试策略，我们需要创建一个错误发生之后 2 秒再发出值的通知者。</p>
<p>接下来我们来尝试用 <code>timer</code> 来创建一个通知者，这个 <code>timer</code> 函数接受两个值：</p>
<ul>
<li>一个在第一个值发出之前的初始延迟</li>
<li>一个我们希望周期性发出值时的周期性延迟</li>
</ul>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-8.png" alt=""></p>
<p>我们可以看到，第一个值 0 在 3 秒之后才发出，然后每隔 1 秒发出一个值。</p>
<p>注意第二个参数是可选的，比如在我们希望在只发出一个值 0 之后就结束。</p>
<p>接下来我们来看看如何如何结合 <code>retryWhen</code> 和 <code>delayWhen</code> 操作符。</p>
<h1 id="delayWhen-操作符"><a href="#delayWhen-操作符" class="headerlink" title="delayWhen 操作符"></a>delayWhen 操作符</h1><p>一件很重要的事情就是，定义通知者的函数只会被调用一次，因此我们只有一次机会来定义这个确定何时重试的通知者。</p>
<p>我们将要获取 Errors Observable，然后应用在 <code>delayWhen</code> 操作符上来定义通知者。</p>
<p>来在这张子弹图上想一想，源 Observable a-b-c 是 Errors Observable，会随着时间发出失败的 HTTP 错误：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-9.png" alt=""></p>
<h2 id="delayWhen-操作符的拆解"><a href="#delayWhen-操作符的拆解" class="headerlink" title="delayWhen 操作符的拆解"></a>delayWhen 操作符的拆解</h2><p>我们通过这张图来学习一下：</p>
<ul>
<li>输入的 Errors Observable 的每个值都会被延迟之后展示在输出 Observable 中</li>
<li>每个值的延迟可以不同，并且将会被用非常灵活的方式创建</li>
<li>为了确定延迟，我们将会每个输入的 Errors Observable 的值调用传递给 <code>delayWhen</code> 的函数（也叫作持续时间选择函数，duration selector function））</li>
<li>这个函数将会发出一个将会决定每个值发出之后的延迟</li>
<li>a-b-c 中的每一个值都有自己的持续时间选择器（duration selector Observable），他最终会发出一个值（可以是任何值），然后结束</li>
<li>当三个持续时间选择器中的每个发出值的时候，对应的输入值 a-b-c 就会在最后的输出中展示</li>
<li>注意值 <code>b</code> 在 <code>c</code> 之后出现，这是很正常的</li>
<li>因为 <code>b</code> 持续时间选择器在 <code>c</code> 持续时间选择器之后发出值</li>
</ul>
<h2 id="实施延迟重试策略"><a href="#实施延迟重试策略" class="headerlink" title="实施延迟重试策略"></a>实施延迟重试策略</h2><p>让我们现在来把这些都放到一起，看看我们怎样按顺序在 2 秒后重试每一个发生错误的 HTTP 请求。</p>
<figure class="highlight typescript"><table><tr><td class="gutter"><pre><span class="line">1</span><br><span class="line">2</span><br><span class="line">3</span><br><span class="line">4</span><br><span class="line">5</span><br><span class="line">6</span><br><span class="line">7</span><br><span class="line">8</span><br><span class="line">9</span><br><span class="line">10</span><br><span class="line">11</span><br><span class="line">12</span><br><span class="line">13</span><br><span class="line">14</span><br><span class="line">15</span><br><span class="line">16</span><br><span class="line">17</span><br><span class="line">18</span><br><span class="line">19</span><br></pre></td><td class="code"><pre><span class="line"><span class="keyword">const</span> http$ = <span class="keyword">this</span>.http.get&lt;Course[]&gt;(<span class="string">'/api/courses'</span>)</span><br><span class="line">http$</span><br><span class="line">  .pipe(</span><br><span class="line">    tap(<span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">"HTTP request executed"</span>)),</span><br><span class="line">    map(<span class="function"><span class="params">res</span> =&gt;</span> <span class="built_in">Object</span>.values(res[<span class="string">'payload'</span>])),</span><br><span class="line">    shareReplay(),</span><br><span class="line">    retryWhen(<span class="function"><span class="params">errors</span> =&gt;</span> &#123;</span><br><span class="line">      <span class="keyword">return</span> errors</span><br><span class="line">        .pipe(</span><br><span class="line">          delayWhen(<span class="function"><span class="params">()</span> =&gt;</span> timer(<span class="number">2000</span>)),</span><br><span class="line">          tap(<span class="function"><span class="params">()</span> =&gt;</span> <span class="built_in">console</span>.log(<span class="string">'retrying...'</span>)),</span><br><span class="line">        )</span><br><span class="line">    &#125;)</span><br><span class="line">  )</span><br><span class="line">  .subscribe(</span><br><span class="line">    res =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP response'</span>, res),</span><br><span class="line">    err =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP Error'</span>, err),</span><br><span class="line">    () =&gt; <span class="built_in">console</span>.log(<span class="string">'HTTP request completed.'</span>)</span><br><span class="line">  )</span><br></pre></td></tr></table></figure>
<p>来拆解一下：</p>
<ul>
<li>传给 <code>retryWhen</code> 的函数只会调用一次</li>
<li>我们在那个函数中返回一个 Observable，他在任何需要重试的时候就会发送值</li>
<li>每当出现一个错误，<code>delayWhen</code> 操作符就会通过调用 <code>timer</code> 函数来创建一个持续时间选择器（duration selector Observable）</li>
<li>这个持续时间选择器将会在 2 秒后发出 0，然后结束</li>
<li>每当这发生的时候，delayWhen Observable 就会知道输入的错误的延迟已经结束了</li>
<li>只有当延迟结束之后，错误才会在通知者的输出中出现</li>
<li>一旦通知者中的值发出，<code>retryWhen</code> 操作符就会执行重试</li>
</ul>
<h2 id="延迟策略的控制台输出内容"><a href="#延迟策略的控制台输出内容" class="headerlink" title="延迟策略的控制台输出内容"></a>延迟策略的控制台输出内容</h2><p>下面是某个 HTTP 请求，重试了 5 次，并且其中 4 次报错的情况：</p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-10.png" alt=""></p>
<p><img src="https://s3-us-west-1.amazonaws.com/angular-university/blog-images/rxjs-error-handling/rxjs-error-handling-11.png" alt=""></p>
<p>可以看到与预期一样，重试在错误发生 2 秒之后才会进行。</p>

    </div>

    
    
    

      <footer class="post-footer">
          <div class="post-tags">
              <a href="/hais-notebook/tags/%E5%85%A5%E9%97%A8/" rel="tag"># 入门</a>
          </div>

        


        
    <div class="post-nav">
      <div class="post-nav-item">
    <a href="/hais-notebook/2021/02/13/Rails-Demo/" rel="prev" title="Rails 的项目搭建">
      <i class="fa fa-chevron-left"></i> Rails 的项目搭建
    </a></div>
      <div class="post-nav-item">
    <a href="/hais-notebook/2021/03/03/Tools-Webpack-Core/" rel="next" title="Webpack 核心原理">
      Webpack 核心原理 <i class="fa fa-chevron-right"></i>
    </a></div>
    </div>
      </footer>
    
  </article>
  
  
  

  </div>


          </div>
          

<script>
  window.addEventListener('tabs:register', () => {
    let activeClass = CONFIG.comments.activeClass;
    if (CONFIG.comments.storage) {
      activeClass = localStorage.getItem('comments_active') || activeClass;
    }
    if (activeClass) {
      let activeTab = document.querySelector(`a[href="#comment-${activeClass}"]`);
      if (activeTab) {
        activeTab.click();
      }
    }
  });
  if (CONFIG.comments.storage) {
    window.addEventListener('tabs:click', event => {
      if (!event.target.matches('.tabs-comment .tab-content .tab-pane')) return;
      let commentClass = event.target.classList[1];
      localStorage.setItem('comments_active', commentClass);
    });
  }
</script>

        </div>
          
  
  <div class="toggle sidebar-toggle">
    <span class="toggle-line toggle-line-first"></span>
    <span class="toggle-line toggle-line-middle"></span>
    <span class="toggle-line toggle-line-last"></span>
  </div>

  <aside class="sidebar">
    <div class="sidebar-inner">

      <ul class="sidebar-nav motion-element">
        <li class="sidebar-nav-toc">
          文章目录
        </li>
        <li class="sidebar-nav-overview">
          站点概览
        </li>
      </ul>

      <!--noindex-->
      <div class="post-toc-wrap sidebar-panel">
          <div class="post-toc motion-element"><ol class="nav"><li class="nav-item nav-level-1"><a class="nav-link" href="#Observable-中的约定与错误处理"><span class="nav-number">1.</span> <span class="nav-text">Observable 中的约定与错误处理</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#RxJS-中的-subscribe-方法与-error-回调"><span class="nav-number">2.</span> <span class="nav-text">RxJS 中的 subscribe 方法与 error 回调</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#完成行为的举例"><span class="nav-number">2.1.</span> <span class="nav-text">完成行为的举例</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#subscribe-方法中的-error-回调函数的局限性"><span class="nav-number">2.2.</span> <span class="nav-text">subscribe 方法中的 error 回调函数的局限性</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#catchError-操作符"><span class="nav-number">3.</span> <span class="nav-text">catchError 操作符</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#catchError-是如何工作的？"><span class="nav-number">3.1.</span> <span class="nav-text">catchError 是如何工作的？</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#当错误发生时会怎样？"><span class="nav-number">3.2.</span> <span class="nav-text">当错误发生时会怎样？</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#捕获并替代策略（The-Catch-and-Replace-Strategy）"><span class="nav-number">4.</span> <span class="nav-text">捕获并替代策略（The Catch and Replace Strategy）</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#捕获并重抛策略（The-Catch-and-Rethrow-Strategy）"><span class="nav-number">5.</span> <span class="nav-text">捕获并重抛策略（The Catch and Rethrow Strategy）</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#拆解捕获并重抛策略"><span class="nav-number">5.1.</span> <span class="nav-text">拆解捕获并重抛策略</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#在-Observable-链条中使用多次-catchError"><span class="nav-number">6.</span> <span class="nav-text">在 Observable 链条中使用多次 catchError</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#Finalize-操作符"><span class="nav-number">7.</span> <span class="nav-text">Finalize 操作符</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#Finalize-操作符的例子"><span class="nav-number">7.1.</span> <span class="nav-text">Finalize 操作符的例子</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#重试策略（The-Retry-Strategy）"><span class="nav-number">8.</span> <span class="nav-text">重试策略（The Retry Strategy）</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#什么时候重试？"><span class="nav-number">8.1.</span> <span class="nav-text">什么时候重试？</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#RxJS-retryWhen-操作符的子弹图"><span class="nav-number">9.</span> <span class="nav-text">RxJS retryWhen 操作符的子弹图</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#拆解-retryWhen-是如何工作的"><span class="nav-number">9.1.</span> <span class="nav-text">拆解 retryWhen 是如何工作的</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#创建一个通知者（Notification-Observable）"><span class="nav-number">10.</span> <span class="nav-text">创建一个通知者（Notification Observable）</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#立即重试策略（Immediate-Retry-Strategy）"><span class="nav-number">11.</span> <span class="nav-text">立即重试策略（Immediate Retry Strategy）</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#立即重试策略的控制台输出内容"><span class="nav-number">11.1.</span> <span class="nav-text">立即重试策略的控制台输出内容</span></a></li></ol></li><li class="nav-item nav-level-1"><a class="nav-link" href="#延迟重试策略（Delayed-Retry-Strategy）"><span class="nav-number">12.</span> <span class="nav-text">延迟重试策略（Delayed Retry Strategy）</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#计时器（Timer-Observable）创建函数"><span class="nav-number">13.</span> <span class="nav-text">计时器（Timer Observable）创建函数</span></a></li><li class="nav-item nav-level-1"><a class="nav-link" href="#delayWhen-操作符"><span class="nav-number">14.</span> <span class="nav-text">delayWhen 操作符</span></a><ol class="nav-child"><li class="nav-item nav-level-2"><a class="nav-link" href="#delayWhen-操作符的拆解"><span class="nav-number">14.1.</span> <span class="nav-text">delayWhen 操作符的拆解</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#实施延迟重试策略"><span class="nav-number">14.2.</span> <span class="nav-text">实施延迟重试策略</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#延迟策略的控制台输出内容"><span class="nav-number">14.3.</span> <span class="nav-text">延迟策略的控制台输出内容</span></a></li></ol></li></ol></div>
      </div>
      <!--/noindex-->

      <div class="site-overview-wrap sidebar-panel">
        <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
  <p class="site-author-name" itemprop="name">Harvey Zhang</p>
  <div class="site-description" itemprop="description">小海的笔记本</div>
</div>
<div class="site-state-wrap motion-element">
  <nav class="site-state">
      <div class="site-state-item site-state-posts">
          <a href="/hais-notebook/archives/">
        
          <span class="site-state-item-count">84</span>
          <span class="site-state-item-name">日志</span>
        </a>
      </div>
      <div class="site-state-item site-state-categories">
            <a href="/hais-notebook/categories/">
          
        <span class="site-state-item-count">29</span>
        <span class="site-state-item-name">分类</span></a>
      </div>
      <div class="site-state-item site-state-tags">
            <a href="/hais-notebook/tags/">
          
        <span class="site-state-item-count">15</span>
        <span class="site-state-item-name">标签</span></a>
      </div>
  </nav>
</div>



      </div>

    </div>
  </aside>
  <div id="sidebar-dimmer"></div>


      </div>
    </main>

    <footer class="footer">
      <div class="footer-inner">
        

<div class="copyright">
  
  &copy; 
  <span itemprop="copyrightYear">2021</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">Harvey Zhang</span>
</div>
  <div class="powered-by">由 <a href="https://hexo.io/" class="theme-link" rel="noopener" target="_blank">Hexo</a> 强力驱动 v4.2.0
  </div>
  <span class="post-meta-divider">|</span>
  <div class="theme-info">主题 – <a href="https://theme-next.org/" class="theme-link" rel="noopener" target="_blank">NexT.Gemini</a> v7.7.0
  </div>

        








      </div>
    </footer>
  </div>

  
  <script src="/hais-notebook/lib/anime.min.js"></script>
  <script src="/hais-notebook/lib/velocity/velocity.min.js"></script>
  <script src="/hais-notebook/lib/velocity/velocity.ui.min.js"></script>

<script src="/hais-notebook/js/utils.js"></script>

<script src="/hais-notebook/js/motion.js"></script>


<script src="/hais-notebook/js/schemes/pisces.js"></script>


<script src="/hais-notebook/js/next-boot.js"></script>




  




  
<script src="/hais-notebook/js/local-search.js"></script>













  

  

  

</body>
</html>
